# -*- coding: utf-8 -*-
"""k-means clustering_damin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1imrn7d2yk75YEw_w_PXM45iAqeqFG6WH
"""

# Tugas Damin 1 - 1301170142

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.DataFrame({
    'x': [5, 3, 8, 5, 7, 5, 7, 21, 23, 26, 22, 20, 24, 21, 27, 28, 23, 27, 25, 27, 23, 26, 24, 26, 25, 14, 17, 15, 13, 18, 14, 12, 18, 15, 15, 16],
    'y': [8, 4, 6, 4, 2, 3, 5, 25, 25, 24, 24, 23, 26, 28, 12, 11, 14, 10, 12, 14, 16, 14, 18, 18, 16, 10, 14, 17, 11, 16, 17, 14, 13, 14, 16, 13]
})

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=4)
kmeans. fit(df)

labels = kmeans.predict(df)
centroids = kmeans.cluster_centers_

colmap = {1:'r', 2:'g', 3:'b', 4:'y'}

fig = plt.figure(figsize=(5,5))
colors = map(lambda x: colmap[x+1], labels)
colors1 = list(colors)
plt.scatter(df['x'], df['y'], color=colors1, alpha=0.5, edgecolor='k')
for idx, centroid in enumerate(centroids):
  plt.scatter(*centroid, color=colmap[idx+1])
plt.xlim(0,30)
plt.ylim(0,30)

print ('n cluster = 4')
plt.show()