# -*- coding: utf-8 -*-
"""AgglomerativeClustering_Damin_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XpFBW9WfHsewu-GUZt0xQ109aWSsrwJ-
"""

# Tugas damin 2 - 1301170142

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering

# Data yang sama dengan tugas sebelumnya
points = pd.DataFrame({
    'x': [5, 3, 8, 5, 7, 5, 7, 21, 23, 26, 22, 20, 24, 21, 27, 28, 23, 27, 25, 27, 23, 26, 24, 26, 25, 14, 17, 15, 13, 18, 14, 12, 18, 15, 15, 16],
    'y': [8, 4, 6, 4, 2, 3, 5, 25, 25, 24, 24, 23, 26, 28, 12, 11, 14, 10, 12, 14, 16, 14, 18, 18, 16, 10, 14, 17, 11, 16, 17, 14, 13, 14, 16, 13]
})

# plot the dataset
plt.scatter(points['x'],points['y'])

dendrogram = sch.dendrogram(sch.linkage(points,method='ward'))

#Perform the actual Clustering
hc = AgglomerativeClustering(n_clusters = 4, affinity='euclidean', linkage='ward')

y_hc=hc.fit_predict(points)
plt.scatter(df['x'],df['y'], c=y_hc, cmap='rainbow')